### ISSUE TITLE
Radiovis monitor

### ISSUE THREAD

**Issue by the-glu** [ebu/radiodns-plugit#37]
Radiovis monitor

**Comment by mhabegger** [comment]
Anybody remembers what this issue was about ? @barroco @coinchon

**Comment by coinchon** [comment]
It may be a a page showing the vis from hosted stations (not all of them in one page but to be able to select).
I don't really remember ...

**Comment by mhabegger** [comment]
Solved.
Implemented button on RadioDNS Manager. And We have the EIS Template for creating wall pages for showing mlutiple stations.
