### ISSUE TITLE
Proposal: Merge logo and radiovis galleries

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#39]
At the moment, there are 2 distinct picture galleries for RadioVIS static images and station logo. 
It would be more useful to have a single gallery for the selection of station logo and radiovis static. This would avoid to upload the same images twice.
This new gallery should indicate the resolution of uploaded pictures.  
The station logo should in principle be uploaded with 600x600 and then other sizes are automatically generated but when 600x600 is not available then 320x240 should be used and the 600x600 automatically generated.

**Comment by mhabegger** [comment]
We won't implement this as the two feature have very particular requirements for size.
VIS Images always are only 320x240 while EPG Logos need various sizes like 32x32 112x32, etc. 600x600.

Thus I close this issue.
