### ISSUE TITLE
Create shortname for orga

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#40]
Create a shortname attribute for each organisation.
This attribute should have no white space of special characters and be limited in size (8 or 16 characters)
This will be helpful to create specific domain name for each organisation (for example rts-chssr.rdns.ebu.io)

**Comment by mhabegger** [comment]
We used the EBU Codops that come through the koi Platform.
This allows to create specific DNS entries and separate the Service Providers and thus create more concise EPG XML Files.
