### ISSUE TITLE
Unique domain per orga

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#41]
At the moment, all entries are under the same domain.
This is problematic for EPG as the XSI  (<domain>/radiodns/epg/XSI.xml) file get very big and contains all entries from different organisations. Same for program information (PI).
Having a unique domain name per orga would allow to have separate XSI files.

**Comment by mhabegger** [comment]
This is also implemented and related to #40
We introduced the Service Provider in the latest release.
