### ISSUE TITLE
FQDN with special characters

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#63]
When a station name contains special characters (with accent), then they are removed in the FQDN.
It would be better to replace them with non-accentuated characters.

For example "Radio Clásica" FQDN becomes radioclsica.esrtve.radio.ebu.io.
it should be radioclasica.esrtve.radio.ebu.io.

**Comment by mhabegger** [comment]
Solved. We convert to the nearest ASCII if there is any otherwise we drop the character.
