### ISSUE TITLE
Service Information path is not working

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#65]
The path to get the Service Information file according to the latest specfication (http://www.etsi.org/deliver/etsi_ts/102800_102899/102818/03.01.01_60/ts_102818v030101p.pdf) is not working (or is not generated) and leads to a 404 error.

Example: http://chrsi.epg.radio.ebu.io/radiodns/spi/3.1/SI.xml

**Comment by mhabegger** [comment]
XSI Works for up to v2 : http://chrsi.epg.radio.ebu.io/radiodns/epg/XSI.xml
V 3.1 is not completed at this time and thus not activate.

**Comment by mhabegger** [comment]
This is implemented in latest release. Please test.

**Comment by coinchon** [comment]
It works, thanks
