### ISSUE TITLE
Wrong XSI file

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#66]
The XSI file generated is wrong and corresponds to another station.

Example with RSI on 
http://chrsi.epg.radio.ebu.io/radiodns/epg/XSI.xml  or http://chrsi.epg.radio.ebu.io:80/radiodns/epg/XSI.xml

Try reloading, sometimes the correct XML appears but disappear again when reloading.

**Comment by mhabegger** [comment]
This is resolved.
Was due to caching ot the page that did not take into account the hostname
