### ISSUE TITLE
RadioVIS service not working

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#67]
RadioVIS service is working when monitoring on the web player. However, testing on the firled with a Revo Axis or Samsung Galaxy, it doesn't display. The RadioVIS service is working on these receiver with the same conditions but with stations that are on RadioDNS Manager 2.0

**Comment by coinchon** [comment]
Seems to work only in certain conditions, when the frequency is present in My Channel. In case of there's only a wildcard (*) but not the frequency, it is not working.

**Comment by mhabegger** [comment]
Solved.
