### ISSUE TITLE
Search field problem

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#72]
Search field for displaying only channels from a particular station has a problem, when typing a station in the field, all channels still appear.

**Comment by mhabegger** [comment]
Perhaps due to spaces that would then search for "any word". Use quotation marks to search for an exact match.

**Comment by coinchon** [comment]
Effectively typing "Radio 3" in search field of RTVE for example still display many of the other channels...

**Comment by mhabegger** [comment]
Works over here.
Please detail browser and version.

Showing 1 to 216 of 216 entries (filtered from 904 total entries)

**Comment by mhabegger** [comment]
@coinchon please advise

**Comment by coinchon** [comment]
It seems there's an issue with Firefox but it works on Chrome, however it becomes very slow when there are lots of channels (test with RTVE). If there are spaces in the search it doesn't work (for example Radio 5 shows all Radio but Radio5 filters correctly despite the Station name is Radio 5)
