### ISSUE TITLE
Logo gallery edit

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#73]
It's not possible to edit an entry in the logo gallery (to change the name) without having to re-upload the image.

**Comment by mhabegger** [comment]
This is solved in the latest release. Please test and close

**Comment by coinchon** [comment]
It works for RadioVIS gallery but edit doesn't work for Logo Gallery (404 when editing and pressing save)

**Comment by mhabegger** [comment]
solved for ServiceProvider Logos as well in latest release.

**Comment by coinchon** [comment]
ok, it works, thank you
