### ISSUE TITLE
XML SI issues

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#74]
Genre (5.13)

The specification gives the form as:

\<genre href="urn:tva:metadata:cs:ContentCS:2004:3.6.10">Hit-Chart/Song Requests\</genre>

The EBU have something akin to the old DAB EPG format:

\<genre href="urn:tva:metadata:cs:ContentCS:2011:2.1.4">
\<name>Documentary\</name>
\</genre>

Radiodns (6.6)

The EBU have:

\<radiodns fqdn="franceculture.frsrf.radio.ebu.io.” serviceIdentifier="franceculture_frsrf_ebu_102"/>

The FQDN must be a valid internet domain (although, see below).  The trailing period makes this not valid.

The Service Identifier must be a maximum of 16 characters in the range [a-z][0-9]. What they have is too long and contains underscores.

**Comment by mhabegger** [comment]
This is solved in the latest release.
We removed the 'name' tag and shortened the serviceidentifier and removed underscores.

**Comment by coinchon** [comment]
It works, thanks
