### ISSUE TITLE
Select organisation of user by default

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#75]
If possible, it would be beneficial to have the organization of the user who is connected selected by default (in the dropdown list in the bottom left of the page) when he logs in.
At the moment, it is "visitor" by default what leads to email from users asking why they have no codeops defined.

**Comment by mhabegger** [comment]
this is implemented. @coinchon please test and close

**Comment by coinchon** [comment]
it doesn't work (test using impersonate function and going to RadioDNS manager from the project page)
