### ISSUE TITLE
change IP channel declaration

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#78]
Change are needed in the IP channel definition.
1) FQDN and ServiceIdentifier are not derived from streaming URL but are either defined by the platform or the user. 
2) These 2 fields must be clearly visible to the user so that they can include it in their stream metadata (ICY-URL).
3) There's no registration of IP channel so they must not appear in the zone file.
4) Doing an HTTP query on the FQDN/ServiceIdentifier could either return a page or a HTTP 302 to the website of the station (as advised in 6.2.1.1 of TS103270).
Many IP channels can exist for the same station but with different bitrate, investigate if this should be either managed as one channel containing all of them or different channel. Another option is to keep declaration of streaming channels in Service Following section.

**Comment by mhabegger** [comment]
3) is solved
can we consider this as closed ?

**Comment by coinchon** [comment]
ok, thank you. I will add 4) as a new enhancement issue.
