### ISSUE TITLE
SI file incomplete, station missing if no channels turned on

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#79]
The SI document doesn't contain the stations if the corresponding channel (bearer) that are not turned on.
The SI document should contain at least the station and logo even if no channel is turned on (but will still contain the FQDN).

We should reconsider the "turn on/off" functionality. It was an feature from Manager 1.0 but that is not really useful nowdays other than activating frequencies instead of the wildcard.
To be discussed.

**Comment by mhabegger** [comment]
The current release will list all station that have radio_epg enabled. Even if they have no channel or if no channel has service following enabled.
@coinchon please check and close.

**Comment by coinchon** [comment]
It works thank you (however we still have to turn on bearer manually, what is problematic when there are thousands of channels for station).
