### ISSUE TITLE
Multiple stations on the same channel

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-plugit#80]
It happens sometimes that 2 radio stations share the same channel using the time. 
For example: The stations and channels NRK Super and NRK Folkemusikk share the same SID and EID. NRK super are on air from 06:00 - 21:00. NRK Folkemusikk is on air from 21:00 - 06:00. 

Investigate the possibility to handle this case (with timers) as a possible enhancement.

**Comment by mhabegger** [comment]
This does not make sense at the moment and will not be implemented.
